packages:
  - "starter"
  - "simple-test"
  - "client-server"
  - "serverless"
  - "web-worker"
  - "monorepo-setup"
  - "monorepo-setup/packages/**"
  - "custom-handler"
  - "server-context"
  - "fullstack-framework"
